preload = /home/adtyn/Media/wallpapers/wp15026922-4k-white-minimalist-wallpapers.webp

#if more than one preload is desired then continue to preload other backgrounds
# .. more preloads
#set the default wallpaper(s) seen on initial workspace(s) --depending on the number of monitors used
wallpaper = , /home/adtyn/Media/wallpapers/wp15026922-4k-white-minimalist-wallpapers.webp

#enable splash text rendering over the wallpaper
splash = false

#fully disable ipc
# ipc = off

