#### Alias and Exports ####
# Alias
alias codium='codium --enable-features=UseOzonePlatform --ozone-platform=wayland --disable-compositing'
alias mongo='setsid mongodb-compass > /dev/null 2>&1 < /dev/null &'
alias archvm='runbg qemu-system-x86_64 -enable-kvm -cpu host -m 6G -smp 8 -drive file=/run/media/adtyn/HP/os/arch/arch-linux-i.img,if=virtio,format=qcow2 -cdrom /run/media/adtyn/HP/os/arch/arch-linux.iso -boot order=d -device virtio-keyboard-pci -device virtio-mouse-pci -device virtio-gpu-pci &'
alias mgba-qt='QT_QPA_PLATFORM=xcb mgba-qt'

# Exports
export PATH="$HOME/bin:$PATH"
export PATH="$HOME/flutter/bin:$PATH"

# FastFetch Fix
FASTFETCH_LOCKFILE="/tmp/.fastfetch_shown_$(whoami)"

is_first_terminal() {
    ps -u "$USER" -o tty=,comm= |
    awk '$2 == "bash" && $1 ~ /^pts/' |
    wc -l | grep -q '^1$'
}

if [ ! -f "$FASTFETCH_LOCKFILE" ] && is_first_terminal; then
    fastfetch
    touch "$FASTFETCH_LOCKFILE"
fi

cleanup_fastfetch_lock() {
    local count
    count=$(ps -u "$USER" -o tty=,comm= |
            awk '$2 == "bash" && $1 ~ /^pts/' |
            wc -l)
    if [ "$count" -le 1 ]; then
        rm -f "$FASTFETCH_LOCKFILE"
    fi
}

trap cleanup_fastfetch_lock EXIT

# Nix-Shell fix
nix-shell() {
  export NIXPKGS_ALLOW_UNFREE=1
  command nix-shell "$@"
}

# Disown Fix
runbg(){
  setsid "$@" > /dev/null 2>&1 < /dev/null &
}

